### ISSUE TITLE
OBJ Files are missing from the repo

### ISSUE THREAD

**Issue by SamXiaosheng** [Twinklebear/zed-vive-mr#1]

**Comment by Twinklebear** [comment]
Sorry, I forgot to include the OBJ files in the repo. I should have time by the end of next week to get these added, unfortunately I'm tied up til then with some other projects. Once I update it I'd be interested in what you're working on with the ZED!

**Comment by Twinklebear** [comment]
I've added the OBJ files in b62cd87c8ae6ae12e8b17214af1d36988a831d05 , let me know if you run into any issues

**Comment by SamXiaosheng** [comment]
Thank you for your help. i will try against.
